site_name: C++ Book
theme:
  name: material
  features:
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
   - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/David-Zhang-test
copyright: Copyright &copy; 2022 - 2023 David John